### ISSUE TITLE
CUETools.Flake --vbr encodes wrong

### ISSUE THREAD

**Issue by H2Swine** [gchudov/cuetools.net#220]
Running the encoder with --vbr 1 to --vbr 4 sometimes yields lossy results. Examples given at https://hydrogenaud.io/index.php/topic,123016 - with a file as well.

**Comment by c72578** [comment]
@H2Swine Thanks for reporting this issue also here at the CUETools github repo.
The issue can be reproduced using the given example from https://hydrogenaud.io/index.php/topic,123016.msg1016175.html#msg1016175 the following way:
```cmd
CUETools.Flake.exe -q -8 -V --vbr 0 "foo.flac" -o "foo_vbr_0.flac"
CUETools.Flake.exe -q -8 -V --vbr 1 "foo.flac" -o "foo_vbr_1.flac"
CUETools.Flake.exe -q -8 -V --vbr 2 "foo.flac" -o "foo_vbr_2.flac"
CUETools.Flake.exe -q -8 -V --vbr 3 "foo.flac" -o "foo_vbr_3.flac"
CUETools.Flake.exe -q -8 -V --vbr 4 "foo.flac" -o "foo_vbr_4.flac"

metaflac --show-md5sum *.flac
foo_vbr_0.flac:7293d3b213a1281d6ab96ee800aade56
foo_vbr_1.flac:7293d3b213a1281d6ab96ee800aade56
foo_vbr_2.flac:7293d3b213a1281d6ab96ee800aade56
foo_vbr_3.flac:7293d3b213a1281d6ab96ee800aade56
foo_vbr_4.flac:7293d3b213a1281d6ab96ee800aade56

flac -t foo_vbr_*.flac

flac 1.4.1
Copyright (C) 2000-2009  Josh Coalson, 2011-2022  Xiph.Org Foundation
flac comes with ABSOLUTELY NO WARRANTY.  This is free software, and you are
welcome to redistribute it under certain conditions.  Type `flac' for details.

foo_vbr_0.flac: ok
foo_vbr_1.flac: ERROR, MD5 signature mismatch
foo_vbr_2.flac: ERROR, MD5 signature mismatch
foo_vbr_3.flac: ERROR, MD5 signature mismatch
foo_vbr_4.flac: ERROR, MD5 signature mismatch
```

**Comment by c72578** [comment]
Tests with older versions of CUETools show the following. The issue is not immediately obvious down to CUETools 2.0.8. In version 2.0.7 and earlier, an `Exception` is thrown during encoding of the affected example file:

- CUETools 2.0.8
```cmd
CUETools.Flake.exe -q -8 --verify -v 0 "foo.flac" -o "foo_vbr_0_2.0.8.flac"
CUETools.Flake.exe -q -8 --verify -v 1 "foo.flac" -o "foo_vbr_1_2.0.8.flac"
CUETools.Flake.exe -q -8 --verify -v 2 "foo.flac" -o "foo_vbr_2_2.0.8.flac"
CUETools.Flake.exe -q -8 --verify -v 3 "foo.flac" -o "foo_vbr_3_2.0.8.flac"
CUETools.Flake.exe -q -8 --verify -v 4 "foo.flac" -o "foo_vbr_4_2.0.8.flac"

metaflac --show-md5sum foo_vbr_*2.0.8.flac
foo_vbr_0_2.0.8.flac:7293d3b213a1281d6ab96ee800aade56
foo_vbr_1_2.0.8.flac:7293d3b213a1281d6ab96ee800aade56
foo_vbr_2_2.0.8.flac:7293d3b213a1281d6ab96ee800aade56
foo_vbr_3_2.0.8.flac:7293d3b213a1281d6ab96ee800aade56
foo_vbr_4_2.0.8.flac:7293d3b213a1281d6ab96ee800aade56

flac -t foo_vbr_*2.0.8.flac

flac 1.4.1
Copyright (C) 2000-2009  Josh Coalson, 2011-2022  Xiph.Org Foundation
flac comes with ABSOLUTELY NO WARRANTY.  This is free software, and you are
welcome to redistribute it under certain conditions.  Type `flac' for details.

foo_vbr_0_2.0.8.flac: ok
foo_vbr_1_2.0.8.flac: ERROR, MD5 signature mismatch
foo_vbr_2_2.0.8.flac: ERROR, MD5 signature mismatch
foo_vbr_3_2.0.8.flac: ERROR, MD5 signature mismatch
foo_vbr_4_2.0.8.flac: ERROR, MD5 signature mismatch
```
- CUETools 2.0.7
```cmd
CUETools.Flake.exe -q -8 --verify -v 0 "foo.flac" -o "foo_vbr_0_2.0.7.flac"

CUETools.Flake.exe -q -8 --verify -v 1 "foo.flac" -o "foo_vbr_1_2.0.7.flac"

Unhandled Exception: System.Exception: validation failed!
   at CUETools.Codecs.FLAKE.FlakeWriter.output_frame()
   at CUETools.Codecs.FLAKE.FlakeWriter.Write(AudioBuffer buff)
   at CUETools.FlakeExe.Program.Main(String[] args)

CUETools.Flake.exe -q -8 --verify -v 2 "foo.flac" -o "foo_vbr_2_2.0.7.flac"

Unhandled Exception: System.Exception: validation failed!
   at CUETools.Codecs.FLAKE.FlakeWriter.output_frame()
   at CUETools.Codecs.FLAKE.FlakeWriter.Write(AudioBuffer buff)
   at CUETools.FlakeExe.Program.Main(String[] args)

CUETools.Flake.exe -q -8 --verify -v 3 "foo.flac" -o "foo_vbr_3_2.0.7.flac"

Unhandled Exception: System.Exception: validation failed!
   at CUETools.Codecs.FLAKE.FlakeWriter.output_frame()
   at CUETools.Codecs.FLAKE.FlakeWriter.Write(AudioBuffer buff)
   at CUETools.FlakeExe.Program.Main(String[] args)

CUETools.Flake.exe -q -8 --verify -v 4 "foo.flac" -o "foo_vbr_4_2.0.7.flac"

Unhandled Exception: System.Exception: validation failed!
   at CUETools.Codecs.FLAKE.FlakeWriter.output_frame()
   at CUETools.Codecs.FLAKE.FlakeWriter.Write(AudioBuffer buff)
   at CUETools.FlakeExe.Program.Main(String[] args)

metaflac --show-md5sum foo_vbr_0_2.0.7.flac
foo_vbr_0_2.0.7.flac:7293d3b213a1281d6ab96ee800aade56

flac -t foo_vbr_0_2.0.7.flac

flac 1.4.1
Copyright (C) 2000-2009  Josh Coalson, 2011-2022  Xiph.Org Foundation
flac comes with ABSOLUTELY NO WARRANTY.  This is free software, and you are
welcome to redistribute it under certain conditions.  Type `flac' for details.

foo_vbr_0_2.0.7.flac: ok
```

**Comment by H2Swine** [comment]
How does it verify, really? Does it actually decode? 
If so, would it be possible then to reverse it and get the PCM back?
