### ISSUE TITLE
CTDB and http://cue.tools/ seem dead

### ISSUE THREAD

**Issue by calestyo** [gchudov/cuetools.net#357]
Hey.

Requests to the CTDB seem to fail and http://cue.tools/ gives a:
```
Sorry! This site is experiencing technical difficulties.

Try waiting a few minutes and reloading.

(Cannot access the database)

Backtrace:

#0 /var/www/html/includes/libs/rdbms/loadbalancer/LoadBalancer.php(934): Wikimedia\Rdbms\LoadBalancer->reportConnectionError()
#1 /var/www/html/includes/libs/rdbms/loadbalancer/LoadBalancer.php(901): Wikimedia\Rdbms\LoadBalancer->getServerConnection(0, 'ctwiki-mediawik...', 0)
#2 /var/www/html/includes/libs/rdbms/loadbalancer/LoadBalancer.php(1046): Wikimedia\Rdbms\LoadBalancer->getConnection(-1, Array, 'ctwiki-mediawik...', 0)
#3 /var/www/html/includes/GlobalFunctions.php(2463): Wikimedia\Rdbms\LoadBalancer->getMaintenanceConnectionRef(-1, Array, 'ctwiki-mediawik...')
#4 /var/www/html/includes/cache/localisation/LCStoreDB.php(56): wfGetDB(-1)
#5 /var/www/html/includes/cache/localisation/LocalisationCache.php(449): LCStoreDB->get('en', 'deps')
#6 /var/www/html/includes/cache/localisation/LocalisationCache.php(495): LocalisationCache->isExpired('en')
#7 /var/www/html/includes/cache/localisation/LocalisationCache.php(371): LocalisationCache->initLanguage('en')
#8 /var/www/html/includes/cache/localisation/LocalisationCache.php(408): LocalisationCache->loadItem('en', 'magicWords')
#9 /var/www/html/includes/cache/localisation/LocalisationCache.php(333): LocalisationCache->loadSubitem('en', 'magicWords', 'ns')
#10 /var/www/html/languages/Language.php(3203): LocalisationCache->getSubitem('en', 'magicWords', 'ns')
#11 /var/www/html/includes/MagicWord.php(126): Language->getMagic(Object(MagicWord))
#12 /var/www/html/includes/MagicWordFactory.php(230): MagicWord->load('ns')
#13 /var/www/html/includes/parser/Parser.php(4872): MagicWordFactory->get('ns')
#14 /var/www/html/includes/parser/CoreParserFunctions.php(64): Parser->setFunctionHook('ns', Array, 1)
#15 /var/www/html/includes/parser/Parser.php(528): CoreParserFunctions::register(Object(Parser))
#16 /var/www/html/includes/parser/Parser.php(477): Parser->firstCallInit()
#17 /var/www/html/includes/parser/ParserFactory.php(142): Parser->__construct(Object(MediaWiki\Config\ServiceOptions), Object(MagicWordFactory), Object(LanguageEn), Object(ParserFactory), 'bitcoin\\:|ftp\\:...', Object(MediaWiki\SpecialPage\SpecialPageFactory), Object(MediaWiki\Linker\LinkRendererFactory), Object(NamespaceInfo), Object(MediaWiki\Logger\LegacyLogger), Object(MediaWiki\BadFileLookup), Object(MediaWiki\Languages\LanguageConverterFactory), Object(MediaWiki\HookContainer\HookContainer))
#18 /var/www/html/includes/ServiceWiring.php(817): ParserFactory->create()
#19 /var/www/html/vendor/wikimedia/services/src/ServiceContainer.php(447): Wikimedia\Services\ServiceContainer->{closure}(Object(MediaWiki\MediaWikiServices))
#20 /var/www/html/vendor/wikimedia/services/src/ServiceContainer.php(416): Wikimedia\Services\ServiceContainer->createService('Parser')
#21 /var/www/html/includes/MediaWikiServices.php(1000): Wikimedia\Services\ServiceContainer->getService('Parser')
#22 /var/www/html/includes/Setup.php(793): MediaWiki\MediaWikiServices->getParser()
#23 /var/www/html/vendor/wikimedia/object-factory/src/ObjectFactory.php(172): {closure}()
#24 /var/www/html/includes/StubObject.php(128): Wikimedia\ObjectFactory::getObjectFromSpec(Array)
#25 /var/www/html/includes/DeprecatedGlobal.php(55): StubObject->_newObject()
#26 /var/www/html/includes/StubObject.php(172): DeprecatedGlobal->_newObject()
#27 /var/www/html/includes/StubObject.php(115): StubObject->_unstub('setHook', 5)
#28 /var/www/html/includes/StubObject.php(142): StubObject->_call('setHook', Array)
#29 /var/www/html/extensions/googleAnalyticsLinks/googa.php(32): StubObject->__call('setHook', Array)
#30 /var/www/html/includes/Setup.php(806): wfGAnalyticsExtension()
#31 /var/www/html/includes/WebStart.php(89): require_once('/var/www/html/i...')
#32 /var/www/html/index.php(44): require('/var/www/html/i...')
#33 {main}
```

Thanks, :-)
Chris

**Comment by gchudov** [comment]
The server ran out of space. Should be fixed now

**Comment by calestyo** [comment]
> The server ran out of space. Should be fixed now

Indeed. Thanks for fixing so quickly.

btw: Are you still considering to somehow make the DB available for download? As said previously, I'm not planning to set up a rival service, but I'm merely a bit concerned how quick such valuable data could vanish from the internet.

Maybe one could offer downloads only for all data where the initial entry is older than 6 months, so that it's not worth for anyone to set up a competitor.

**Comment by gchudov** [comment]
I don't mind competition, the more the merrier. The server is doing daily backups, but there's still some work required to make them publicly available. Also currently the backups are made into an s3 bucket under the same AWS account, and for true redundancy they should be cloned somewhere else. Lately i didn't have much free time to work on this, but I'll see what i can do.

**Comment by calestyo** [comment]
> I don't mind competition, the more the merrier.

Well the bad thing, unless there would be some synchronisation between different DB servers, is well.. exactly that different servers would end up having different data, which would IMO harm everyone.
